import "./globals.css";

export const metadata = {
  title: "Alibaba",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body>{children}</body>
    </html>
  );
}
